# -*- coding: utf-8 -*-
"""Analise_dados_Esplori_2025-2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E67amnLrQaL7cxgS3gll6-S4tCbVJUPf
"""

from google.colab import files
uploaded = files.upload()

import zipfile

zip_path = "dataset_eda_ficticio.zip"

with zipfile.ZipFile(zip_path, 'r') as z:
    z.extractall("dados")

# valores nulos de todas as tabelas
import pandas as pd

usuarios = pd.read_csv("dados/usuarios.csv")
estab = pd.read_csv("dados/estabelecimentos.csv")
categorias = pd.read_csv("dados/categorias.csv")
estab_cat = pd.read_csv("dados/estabelecimento_categoria.csv")
checkins = pd.read_csv("dados/checkins.csv")
interacoes = pd.read_csv("dados/interacoes.csv")
promocoes = pd.read_csv("dados/promocoes.csv")

print("USUARIOS")
print(usuarios.head())

print("\nESTABELECIMENTOS")
print(estab.head())

print("\nCATEGORIAS")
print(categorias.head())

print("\nESTAB_CATEGORIA")
print(estab_cat.head())

print("\nCHECKINS")
print(checkins.head())

print("\nINTERACOES")
print(interacoes.head())

print("\nPROMOCOES")
print(promocoes.head())

"""#tratamento do data.set"""

def padronizar_texto(df, coluna):
    df[coluna] = df[coluna].str.lower().str.strip()

padronizar_texto(usuarios, "origem_geografica")
padronizar_texto(estab, "origem_geografica")

print("USUARIOS")
print(usuarios.head())

print("\nESTABELECIMENTOS")
print(estab.head())

"""Foi aplicada padronização textual na coluna origem_geografica (lowercase e trim) para garantir consistência dos dados e evitar divergências causadas por variações de escrita.

#Tratamento de Datas/Horários
"""

checkins["data_hora_checkin"] = pd.to_datetime(
    checkins["data_hora_checkin"], errors="coerce"
)

antes = checkins["data_hora_checkin"].copy()

checkins["data_hora_checkin"] = pd.to_datetime(
    checkins["data_hora_checkin"], errors="coerce"
)

comparacao = pd.DataFrame({
    "ANTES": antes.head(10),
    "DEPOIS": checkins["data_hora_checkin"].head(10)
})

comparacao

"""Tratamento de data e hora
Foi realizada a conversão da coluna de data/hora para o tipo datetime, a fim de padronizar o formato temporal dos registros. A comparação entre os valores antes e depois do tratamento indica que os dados já se encontravam em formato válido, não sofrendo alterações após a conversão. Registros inválidos ou ausentes foram corretamente representados como NaT, garantindo integridade e consistência para análises temporais futuras.

#Remoção de registro inconsistentes
"""

usuarios_antes = usuarios.copy()

usuarios["genero"] = usuarios["genero"].fillna(usuarios["genero"].mode()[0])
usuarios["origem_geografica"] = usuarios["origem_geografica"].fillna(
    usuarios["origem_geografica"].mode()[0]
)
usuarios["efetuou_checkin"] = usuarios["efetuou_checkin"].fillna(False).astype(bool)

usuarios.dropna(subset=["idade"], inplace=True)

usuarios["idade"] = usuarios["idade"].astype(int)

usuarios = usuarios[(usuarios["idade"] >= 18) & (usuarios["idade"] <= 65)]

usuarios.drop_duplicates(inplace=True)

print("ANTES:", usuarios_antes.shape)
print("DEPOIS:", usuarios.shape)

"""Após o tratamento e validação dos dados, o conjunto foi reduzido de 6.018 para 5.673 registros, indicando a remoção de entradas inválidas ou inconsistentes. Essa etapa visa garantir maior qualidade e confiabilidade das análises subsequentes, preservando apenas registros com informações adequadas

#Tratamento da Tabela de Estabelecimentos
"""

estab_antes = estab.copy()

estab["criacao_promocoes"] = estab["criacao_promocoes"].fillna(0)
estab.drop_duplicates(inplace=True)

print("ANTES:", estab_antes.shape)
print("DEPOIS:", estab.shape)

"""Tratamento da tabela de estabelecimentos
Foi realizado o preenchimento de valores ausentes na coluna criacao_promocoes com zero, bem como a verificação e remoção de possíveis duplicatas. A comparação entre as dimensões antes e depois do tratamento indica que o dataset manteve o mesmo número de registros, confirmando a ausência de duplicidades e a integridade da base de estabelecimentos após a limpeza.

#Tratamento da Tabela de Check-ins
"""

checkins_antes = checkins.copy()

checkins.dropna(inplace=True)
checkins.drop_duplicates(inplace=True)

print("ANTES:", checkins_antes.shape)
print("DEPOIS:", checkins.shape)

"""Tratamento da tabela de check-ins
Foi realizada a remoção de registros com valores ausentes e de entradas duplicadas na tabela de check-ins. Como resultado, o conjunto de dados teve seu volume reduzido, preservando apenas registros completos e únicos. Essa etapa é essencial para garantir a confiabilidade das análises relacionadas a padrões de uso, comportamento temporal e conversão dos usuários

Tratamento da Tabela de Interações
"""

interacoes_antes = interacoes.copy()

interacoes["visualizacoes_perfil"] = interacoes["visualizacoes_perfil"].fillna(0).astype(int)
interacoes["saves_favoritos"] = interacoes["saves_favoritos"].fillna(0).astype(int)
interacoes["compartilhamentos"] = interacoes["compartilhamentos"].fillna(0).astype(int)

interacoes.drop_duplicates(inplace=True)

print("ANTES:", interacoes_antes.shape)
print("DEPOIS:", interacoes.shape)

"""Tratamento da tabela de interações
Foi criada uma cópia de segurança da tabela antes do tratamento. Em seguida, os valores ausentes das colunas de interação (visualizacoes_perfil, saves_favoritos e compartilhamentos) foram preenchidos com zero e convertidos para o tipo inteiro, garantindo consistência semântica das métricas. Por fim, registros duplicados foram removidos. Essas etapas asseguram maior confiabilidade e precisão nas análises de engajamento e comportamento dos usuários.

# Tratamento da Tabela de Promoções
"""

promocoes_antes = promocoes.copy()

promocoes["quantidade_disponibilizada"] = promocoes[
    "quantidade_disponibilizada"
].fillna(promocoes["quantidade_disponibilizada"].median())

promocoes["quantidade_utilizada"] = promocoes[
    ["quantidade_utilizada", "quantidade_disponibilizada"]
].min(axis=1)

promocoes.drop_duplicates(inplace=True)

print("ANTES:", promocoes_antes.shape)
print("DEPOIS:", promocoes.shape)

"""Tratamento da tabela de promoções
Foi criada uma cópia de segurança da tabela de promoções antes do tratamento. Valores ausentes na coluna quantidade_disponibilizada foram preenchidos com a mediana, garantindo robustez estatística. Em seguida, foi aplicada uma regra de consistência lógica para assegurar que a quantidade_utilizada não excedesse a quantidade disponibilizada. Por fim, registros duplicados foram removidos. Essas etapas garantem maior integridade e confiabilidade na análise de performance das promoções.

#Análise Preliminar

##Origem Geográfica dos Usuários
"""

usuarios.describe()


usuarios["idade"].median()

usuarios["genero"].value_counts()
usuarios["origem_geografica"].value_counts()

"""Insight: A análise inicial da origem geográfica dos usuários revela forte concentração em Recife e na Região Metropolitana, com queda acentuada da participação à medida que se avança para cidades do interior. Esse padrão indica centralização urbana da base de usuários e sugere a necessidade de segmentações regionais para evitar vieses em análises globais.

##Interações (visualizações, saves e compartilhamentos)
"""

interacoes.describe()

"""Insight: A tabela de interações possui 20.002 registros e não apresenta valores ausentes nas variáveis numéricas analisadas. As visualizações de perfil apresentam média de 5,72 e mediana de 6, com concentração entre 4 e 7 visualizações (IQR), indicando um padrão relativamente estável de consumo de perfis. Já as ações de maior intenção são mais raras: saves/favoritos têm mediana 0 e 75% dos registros até 1 save, enquanto compartilhamentos apresentam mediana 0 e 75% iguais a 0, sugerindo que a maioria das interações não chega ao nível de recomendação/propagação. Esse comportamento caracteriza um funil clássico de engajamento, com maior volume no topo (visualizações) e forte queda em ações de maior compromisso (salvar e compartilhar).

# Uso de Voucher
"""

checkins["faixa_gasto"].value_counts()
checkins["usou_voucher"].value_counts()

"""Insight: A análise preliminar do uso de vouchers indica que a maioria dos registros não envolve promoções, sugerindo que o engajamento ocorre majoritariamente de forma orgânica. No entanto, a presença de uma parcela relevante de interações com voucher demonstra que incentivos promocionais podem influenciar positivamente um segmento específico de usuários, justificando análises comparativas entre comportamentos com e sem uso de voucher.

#Matriz de Correlação (Interações)
"""

interacoes.corr(numeric_only=True)

"""Insight: A matriz de correlação indica que os identificadores (id_usuario e id_estabelecimento) não apresentam relação relevante com métricas de engajamento, como esperado. Observa-se correlação positiva moderada entre visualizacoes_perfil e saves_favoritos (r≈0,28), sugerindo que maior exposição ao perfil aumenta a chance de salvar, embora não seja um fator determinístico. A correlação entre visualizacoes_perfil e compartilhamentos é positiva, porém fraca (r≈0,18), indicando que compartilhar é uma ação menos diretamente associada ao volume de visualizações. Por fim, saves_favoritos e compartilhamentos apresentam correlação muito baixa (r≈0,07), sugerindo comportamentos distintos e/ou baixa frequência de compartilhamento.

#Interações por fez_checkin (médias)
"""

df_merge = interacoes.merge(
    checkins,
    on=["id_usuario", "id_estabelecimento"],
    how="left"
)

df_merge["fez_checkin"] = df_merge["id_checkin"].notnull()

df_merge.groupby("fez_checkin")[[
    "visualizacoes_perfil",
    "saves_favoritos",
    "compartilhamentos"
]].mean()

"""Insight: Ao segmentar as métricas de interação por fez_checkin, observa-se que usuários que realizaram check-in apresentam maiores médias de visualizacoes_perfil (6,21 vs 5,72) e saves_favoritos (0,88 vs 0,68), indicando maior engajamento e intenção antes da conversão. Em contrapartida, compartilhamentos apresenta leve redução no grupo que fez check-in (0,25 vs 0,28), sugerindo que compartilhar pode representar um comportamento distinto — mais social — e não necessariamente relacionado à conversão. Esses resultados reforçam um padrão de funil em que exploração (visualização) e intenção (save) se associam mais diretamente ao check-in.

#Distribuição por Categoria (Top 10)
"""

checkins["id_categoria"].value_counts().head(10)

"""Insight: A distribuição por categoria indica um padrão equilibrado entre as categorias mais recorrentes, sem predominância significativa de um único grupo. As frequências do Top 10 apresentam diferenças reduzidas, sugerindo diversidade de interesses e alta competitividade entre categorias.

#Origem Geográfica (Recorte Atual)
"""

checkins.merge(estab, on="id_estabelecimento")[
    "origem_geografica"
].value_counts()

"""Insight: Mesmo após o recorte aplicado, observa-se forte concentração de registros em Recife e na Região Metropolitana, com queda progressiva da participação em municípios do interior. Esse padrão indica centralização geográfica persistente e reforça a necessidade de segmentações regionais para análises mais equilibradas.

#Distribuição por Hora
"""

usuarios["horario_maior_busca"] = pd.to_datetime(
    usuarios["horario_maior_busca"],
    format="%H:%M:%S",
    errors="coerce"
)

usuarios["hora"] = usuarios["horario_maior_busca"].dt.hour

usuarios["hora"].value_counts().sort_index()

"""Insight:A distribuição por hora mostra concentração das ocorrências no período da tarde, com pico entre 13h e 16h, especialmente às 14h. A atividade cresce ao longo da manhã, mantém-se elevada durante o horário comercial e apresenta queda gradual no período noturno, indicando um padrão predominantemente diurno de uso.

#Estatísticas Descritivas (Interações)
"""

resumo_interacoes = interacoes.describe().T
resumo_interacoes

"""Insight:As estatísticas descritivas da tabela de interações (n=20.002) indicam ausência de valores ausentes nas colunas numéricas analisadas. As visualizações de perfil apresentam média de 5,72 e mediana de 6, com concentração entre 4 e 7 visualizações, sugerindo padrão estável de navegação. Já saves/favoritos possuem mediana 0 e 75% dos registros até 1 save, indicando que salvar é uma ação menos frequente e de maior intenção. Compartilhamentos são ainda mais raros: a mediana e o percentil 75% são 0, evidenciando que a grande maioria das interações não inclui compartilhamento. Esse comportamento caracteriza um funil de engajamento, com maior volume no topo (visualizações) e queda acentuada em ações de maior compromisso (saves e compartilhamentos).

# Processo de **Visualização**

#Faixa etaria do usuario da plataforma
"""

import matplotlib.pyplot as plt
import pandas as pd


usuarios["faixa_etaria"] = pd.cut(
    usuarios["idade"],
    bins=[18,25,35,45,55,65],
    labels=["18-25","26-35","36-45","46-55","56-65"],
    include_lowest=True
)

ordem = ["18-25","26-35","36-45","46-55","56-65"]

demo = usuarios.groupby(
    ["faixa_etaria", "genero"],
    observed=False
).size().unstack()

demo = demo.reindex(ordem)

cores = ["#E07A2F", "#B96A4A", "#6B7A3A", "#8A9450"]

ax = demo.plot(
    kind="bar",
    stacked=True,
    color=cores[:demo.shape[1]]
)

plt.title("Distribuição de usuários por faixa etária e gênero")
plt.xlabel("Faixa etária")
plt.ylabel("Quantidade")


plt.legend(
    title="Gênero",
    bbox_to_anchor=(1.05, 1),
    loc="upper left"
)

plt.tight_layout()
plt.show()

"""Insight:

Observa-se que a distribuição de usuários é relativamente equilibrada entre as faixas etárias analisadas, com leve concentração nas faixas de 26–35 e 56–65 anos, indicando maior presença ou engajamento desses grupos na plataforma. Em todas as faixas etárias, o gênero masculino apresenta participação ligeiramente superior, seguido pelo feminino, enquanto o grupo “não informado” representa uma parcela residual da base.
Esse padrão sugere que não há diferenças significativas de comportamento por gênero entre as faixas etárias, indicando um uso relativamente homogêneo da plataforma nesse aspecto. No entanto, a maior concentração de usuários nas faixas etárias intermediárias e mais altas pode indicar maior engajamento, estabilidade de uso ou maior aderência desse público à proposta da plataforma.
De forma complementar, quando analisados os usuários que realizam check-in, observa-se que estes tendem a apresentar maior nível de engajamento prévio, refletido em mais visualizações e interações, o que sugere que o envolvimento inicial com o conteúdo influencia diretamente a conversão em check-ins.

#

# Taxa de conversão
"""

dicionario_checkin = {
    0: "visualizou",
    1: "check-in",
    -1: "Sem informação"
}

taxa = interacoes.merge(
    usuarios[["id_usuario", "efetuou_checkin"]],
    on="id_usuario",
    how="left"
)

taxa["efetuou_checkin"] = taxa["efetuou_checkin"].fillna(-1)

conv = taxa.groupby(
    "efetuou_checkin",
    observed=False
)["visualizacoes_perfil"].count()

conv.index = conv.index.map(dicionario_checkin)

ordem = ["visualizou", "check-in", "Sem informação"]
conv = conv.reindex(ordem)

cores = ["#6B7A3A", "#E07A2F", "#B96A4A"]

plt.figure(figsize=(7,5))

ax = conv.plot(
    kind="bar",
    color=cores,
    edgecolor="black"
)

plt.title("Conversão: Visualização de Perfil → Check-in")
plt.xlabel("Status do Usuário")
plt.ylabel("Quantidade")


for i, v in enumerate(conv.values):
    plt.text(
        i,
        v + max(conv.values)*0.02,
        str(v),
        ha='center',
        fontweight='bold'
    )

plt.legend().set_visible(False)

plt.tight_layout()
plt.show()

"""insight: As visualizações (11.632) predominam, indicando maior consumo passivo de conteúdo. Os check-ins (7.036) mostram um bom nível de engajamento ativo, representando uma conversão relevante das visualizações. Já a categoria “sem informação” (1.336) é baixa, mas aponta possíveis lacunas na coleta de dados.

Em geral, há um bom nível de engajamento, com forte volume de descoberta e conversão consistente para ações.

# Taxa de oportunidade (drop-off)
"""

taxa["efetuou_checkin"] = taxa["efetuou_checkin"].fillna(0)

total = len(taxa)
convertidos = taxa["efetuou_checkin"].sum()
dropoff = total - convertidos

labels = ["Converteram", "Não converteram"]
values = [convertidos, dropoff]


cores = ["#E07A2F", "#6B7A3A"]

plt.figure(figsize=(7,5))

ax = plt.bar(
    labels,
    values,
    color=cores,
    edgecolor="black"
)

plt.title(
    "Taxa de Conversão (Funil de Oportunidade)",
    fontsize=14,
    fontweight="bold"
)

plt.ylabel("Quantidade")

for i, v in enumerate(values):
    plt.text(i, v + max(values)*0.02, str(v), ha='center')

plt.grid(axis="y", linestyle="--", alpha=0.4)

plt.tight_layout()
plt.show()

"""Insight: A maior parte dos usuários não converteu (14.304), indicando que ainda há perda significativa no funil de oportunidade. Em contrapartida, 5.700 usuários converteram, mostrando que há uma base consistente de engajamento efetivo.

A taxa de conversão é relevante, mas o volume de não conversão evidencia alto potencial de otimização do funil, especialmente nas etapas iniciais de interesse e decisão.

# Performance de promoções
"""

promocoes["taxa_uso"] = (
    promocoes["quantidade_utilizada"] /
    promocoes["quantidade_disponibilizada"]
)

cores = ["#E07A2F", "#6B7A3A", "#B96A4A"]

plt.figure(figsize=(8,5))

plt.hist(
    promocoes["taxa_uso"].dropna(),
    bins=10,
    color="#E07A2F",
    edgecolor="black",
    alpha=0.85
)

plt.title(
    "Distribuição da Taxa de Uso das Promoções",
    fontsize=14,
    fontweight="bold"
)

plt.xlabel("Taxa de uso (0 = não usada | 1 = totalmente usada)")
plt.ylabel("Quantidade de promoções")

plt.grid(axis="y", linestyle="--", alpha=0.4)

plt.tight_layout()
plt.show()

"""Insight :A distribuição sugere que, embora as promoções sejam utilizadas, a maioria não atinge seu potencial máximo de uso, indicando uma oportunidade para otimização de estratégias de marketing e personalização de ofertas

# Retenção de clientes
"""

retencao = checkins.groupby("id_usuario").size()

dist = retencao.value_counts().sort_index()

x = dist.index
y = dist.values

cores = ["#E07A2F", "#B96A4A"]

plt.figure(figsize=(8,5))

bars = plt.bar(
    x,
    y,
    color="#E07A2F",
    edgecolor="black"
)

plt.title(
    "Distribuição de Frequência de Check-ins por Usuário",
    fontsize=14,
    fontweight="bold"
)

plt.xlabel("Número de check-ins")
plt.ylabel("Quantidade de usuários")

for i, v in enumerate(y):
    plt.text(
        x[i],
        v + max(y)*0.02,
        str(v),
        ha='center',
        fontweight='bold'
    )

plt.xticks(x)

plt.grid(axis="y", linestyle="--", alpha=0.4)

plt.tight_layout()
plt.show()

"""Insight: Observa-se uma distribuição fortemente assimétrica, com grande concentração de usuários realizando apenas 1 check-in (84%). À medida que o número de check-ins aumenta, a quantidade de usuários cai drasticamente, indicando baixa recorrência. Usuários com 3 ou mais check-ins representam apenas 1,66%, sugerindo que há poucos usuários altamente engajados e a maioria realiza uso pontual.

# Top 10 estabelecimentos
"""

import matplotlib.pyplot as plt

df = interacoes.merge(
    estab,
    on="id_estabelecimento",
    how="left"
)

top_estab = df["nome_estabelecimento"].value_counts().head(10).reset_index()
top_estab.columns = ["nome_estabelecimento", "checkins"]

top_estab = top_estab.sort_values("checkins")


plt.figure(figsize=(10,6))

plt.barh(
    top_estab["nome_estabelecimento"].astype(str),
    top_estab["checkins"],
    color="#E07A2F",
    edgecolor="black"
)

plt.title("Top 10 Estabelecimentos por Check-in")
plt.xlabel("Quantidade de check-ins")

for i, v in enumerate(top_estab["checkins"]):
    plt.text(v, i, str(v), va='center', fontweight='bold')

plt.grid(axis="x", linestyle="--", alpha=0.4)
plt.tight_layout()
plt.show()

"""Insight: O ranking de check-ins mostra forte concentração no Top 3, com dois líderes praticamente empatados (140 e 138) e um terceiro ainda bem acima do restante (121). Após o Top 3 ocorre um degrau acentuado, e os demais estabelecimentos se agrupam em uma faixa bem próxima (82–85), com empates frequentes, indicando competição equilibrada nessa zona. Observa-se também predominância de categorias como sushi e pizzarias no Top 10, sugerindo preferência do público ou maior atratividade desses tipos de locais. Além disso, a recorrência de nomes associados a bairros (Derby, Bairro Novo, Bongi, Capibaribe) sugere possíveis hotspots geográficos de check-ins, que podem ser explorados em análises por região.

# Check-ins por região
"""

import geopandas as gpd
import matplotlib.pyplot as plt
import pandas as pd
import unicodedata

def normalizar(texto):
    return unicodedata.normalize('NFKD', texto).encode('ascii', 'ignore').decode('utf-8').lower()

regiao = usuarios["origem_geografica"].value_counts().reset_index()
regiao.columns = ["cidade", "qtd_usuarios"]
regiao["cidade"] = regiao["cidade"].apply(normalizar)

url_mun = "https://raw.githubusercontent.com/tbrugz/geodata-br/master/geojson/geojs-26-mun.json"
mun = gpd.read_file(url_mun)
mun["cidade"] = mun["name"].apply(normalizar)

cidades_dataset = regiao["cidade"].unique()
mun_pe = mun[mun["cidade"].isin(cidades_dataset)]

mapa = mun_pe.merge(regiao, on="cidade", how="left")
mapa["qtd_usuarios"] = mapa["qtd_usuarios"].fillna(0)

url_estados = "https://raw.githubusercontent.com/codeforamerica/click_that_hood/master/public/data/brazil-states.geojson"
estados = gpd.read_file(url_estados)

pe = estados[estados["name"] == "Pernambuco"]

fig, ax = plt.subplots(figsize=(10,10))

mapa.plot(
    column="qtd_usuarios",
    cmap="Oranges",
    linewidth=0.3,
    edgecolor="black",
    legend=True,
    ax=ax
)

pe.boundary.plot(
    ax=ax,
    color="black",
    linewidth=1
)

ax.set_title("Top 10 Usuários por Região (Origem Geográfica)", fontsize=14)
ax.axis("off")

plt.show()

print("Arquivos em dados/:")
print(os.listdir("dados"))

import matplotlib.pyplot as plt

regiao = usuarios["origem_geografica"].value_counts().head(10)

plt.figure(figsize=(10,6))

bars = plt.bar(
    regiao.index,
    regiao.values,
    color="#E07A2F",
    edgecolor="black"
)

plt.title("Top 10 Usuários por Região (Origem Geográfica)", fontsize=14, fontweight="bold")
plt.xlabel("Região")
plt.ylabel("Quantidade de Usuários")

plt.xticks(rotation=45, ha="right")


plt.grid(axis="y", linestyle="--", alpha=0.3)

for bar in bars:
    plt.text(
        bar.get_x() + bar.get_width()/2,
        bar.get_height(),
        str(int(bar.get_height())),
        ha='center',
        va='bottom',
        fontweight='bold'
    )

plt.tight_layout()
plt.show()

"""Insight: O gráfico evidencia forte concentração de usuários em Recife (2625), muito acima das demais regiões, indicando centralização geográfica da base. As posições seguintes (Olinda, Jaboatão dos Guararapes e Paulista) reforçam um padrão de predominância da Região Metropolitana do Recife. Cidades do interior (como Caruaru, Garanhuns e Petrolina) aparecem no Top 10, porém com volumes significativamente menores, sugerindo participação mais limitada fora do eixo metropolitano. Esse cenário pode gerar viés em análises agregadas, sendo recomendado comparar regiões com métricas normalizadas (percentuais) ou segmentações como RMR vs interior

# Categorias em destaque
"""

checkins_cat = checkins.merge(
    categorias,
    on="id_categoria",
    how="left"
)

cat = checkins_cat["nome_categoria"].value_counts().head(10)


plt.figure(figsize=(10,6))

bars = plt.bar(
    cat.index.astype(str),
    cat.values,
    color="#E07A2F",
    edgecolor="black"
)

plt.title("Top 10 Categorias Mais Acessadas", fontsize=14, fontweight="bold")
plt.xlabel("Categoria")
plt.ylabel("Quantidade de Acessos")

plt.xticks(rotation=45, ha="right")

plt.grid(axis="y", linestyle="--", alpha=0.3)

# valores em cima das barras
for bar in bars:
    plt.text(
        bar.get_x() + bar.get_width()/2,
        bar.get_height(),
        str(int(bar.get_height())),
        ha='center',
        va='bottom',
        fontweight='bold'
    )

plt.tight_layout()
plt.show()

"""Insight:O gráfico de Top 10 Categorias Mais Acessadas apresenta distribuição relativamente equilibrada (79 a 98 acessos), indicando diversidade de interesses e ausência de uma única categoria dominante. As primeiras posições reforçam forte presença de categorias ligadas a experiências e lazer (Tour Cultural, Show ao vivo, Stand-up Comedy, Pub e Bar/Cerveja Artesanal), sugerindo que os acessos não se limitam à gastronomia. Ainda assim, categorias de alimentação (Sorveteria, Cafeteria, Padaria, Churrascaria e Frutos do Mar) permanecem bem representadas. A proximidade entre os valores do Top 4 e os empates no final indicam um ranking competitivo e sujeito a variações conforme período ou comportamento sazonal.

#Concorrência por categoria
"""

conc = estab_cat.merge(estab, on="id_estabelecimento")
conc = conc.merge(categorias, on="id_categoria")

tabela = conc.groupby(
    ["nome_categoria", "faixa_de_gasto"]
).size().unstack(fill_value=0)

tabela["total"] = tabela.sum(axis=1)
tabela = tabela.sort_values("total", ascending=False).head(10).drop(columns="total")

import matplotlib.pyplot as plt

paleta = {
    "baixo": "#E9C46A",
    "medio": "#F4A261",
    "alto": "#E07A2F"
}

ax = tabela.plot(
    kind="bar",
    figsize=(12,6),
    color=[paleta.get(col, "#E07A2F") for col in tabela.columns]
)

plt.title("Concorrência por Categoria e Faixa de Gasto", fontsize=14, fontweight="bold")
plt.xlabel("Categoria")
plt.ylabel("Quantidade")

plt.xticks(rotation=45, ha="right")

plt.grid(axis="y", linestyle="--", alpha=0.3)

plt.legend(title="Faixa de Gasto")

plt.tight_layout()
plt.show()

"""Insight: O gráfico de concorrência por categoria e faixa de gasto indica predominância da faixa ‘baixo’ na maioria das categorias, sugerindo concentração de oferta/consumo em opções mais acessíveis. Em geral, a faixa ‘médio’ aparece como segundo maior volume, com variações conforme a categoria, enquanto ‘alto’ tende a representar um segmento menor e mais nichado. Categorias de experiência (ex.: Escape Room e Trilha Ecológica) apresentam distribuição relativamente mais equilibrada, indicando possível maior aceitação de gasto médio nesse tipo de atividade. Esse padrão reforça a importância de segmentar análises e estratégias por faixa de gasto, pois o comportamento muda conforme a categoria

# estabelecimento em alta
"""

df = interacoes.merge(estab, on="id_estabelecimento")

top_estab = df.groupby("nome_estabelecimento")["visualizacoes_perfil"].sum().sort_values(ascending=False).head(10)

plt.figure(figsize=(10,6))

plt.bar(
    top_estab.index,
    top_estab.values,
    color="#E07A2F",
    edgecolor="black"
)

plt.title("Top 10 Estabelecimentos por Visualizações de Perfil", fontsize=14, fontweight="bold")
plt.xlabel("Estabelecimento")
plt.ylabel("Visualizações")

plt.xticks(rotation=45, ha="right")
plt.grid(axis="y", linestyle="--", alpha=0)

"""Insight: O gráfico de Top 10 Estabelecimentos por Visualizações de Perfil destaca forte concentração de atenção nos dois primeiros colocados, que apresentam volumes significativamente maiores que os demais. Observa-se um degrau claro entre o Top 2, o terceiro estabelecimento e o grupo restante, que apresenta valores bastante próximos entre si, indicando alta competitividade por visibilidade. A recorrência de estabelecimentos da categoria sushi nas primeiras posições sugere forte atratividade do tipo de oferta. No entanto, visualizações não implicam necessariamente conversão, reforçando a importância de análises complementares que cruzem visualizações com check-ins e interações"""